# Generated by Django 2.2.6 on 2019-11-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('Co_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('duration', models.IntegerField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_provider_name', models.CharField(max_length=32)),
                ('online', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('mail_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('deg_id', models.AutoField(primary_key=True, serialize=False)),
                ('deg_type', models.CharField(max_length=20)),
                ('deg_stream', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='degree_provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deg_provider_name', models.CharField(max_length=32)),
                ('mail_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('mail_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='req_course_mapping',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='degree_enroll_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=32)),
                ('degree_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree_provider')),
            ],
        ),
        migrations.CreateModel(
            name='degree_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('credits', models.IntegerField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='degree_completion_req',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement_name', models.CharField(max_length=20)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='deg_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree_provider'),
        ),
        migrations.CreateModel(
            name='course_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('credits', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course_provider'),
        ),
    ]
