# Generated by Django 2.2.7 on 2019-11-12 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('Co_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('duration', models.IntegerField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_provider',
            fields=[
                ('course_provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_provider_name', models.CharField(max_length=32)),
                ('online', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='degree',
            fields=[
                ('deg_id', models.AutoField(primary_key=True, serialize=False)),
                ('deg_type', models.CharField(max_length=20)),
                ('deg_stream', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='degree_provider',
            fields=[
                ('deg_provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('deg_provider_name', models.CharField(max_length=32)),
                ('mail_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mail_id',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='degree_enroll_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=32)),
                ('degree_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree_provider')),
            ],
        ),
        migrations.CreateModel(
            name='degree_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('credits', models.IntegerField()),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='deg_provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree_provider'),
        ),
        migrations.CreateModel(
            name='course_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('credits', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course_provider'),
        ),
    ]
