# Generated by Django 2.2.7 on 2019-11-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191112_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_provider_id',
            new_name='course_provider',
        ),
        migrations.RenameField(
            model_name='course_enroll',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='course_enroll',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='degree',
            old_name='deg_provider_id',
            new_name='deg_provider',
        ),
        migrations.RenameField(
            model_name='degree_enroll',
            old_name='degree_id',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='degree_enroll',
            old_name='student_id',
            new_name='student',
        ),
        migrations.CreateModel(
            name='req_course_mapping',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='degree_completion_req',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('requirement_name', models.CharField(max_length=20)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree')),
            ],
        ),
    ]
