# Generated by Django 2.2.7 on 2019-11-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191112_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_provider',
            name='password',
        ),
        migrations.RemoveField(
            model_name='degree_provider',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
