# Generated by Django 2.2.6 on 2019-11-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191112_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_provider',
            old_name='course_provider_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='degree_provider',
            old_name='deg_provider_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course_provider', to_field='course_provider_id'),
        ),
        migrations.AlterField(
            model_name='course_enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student', to_field='student_id'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='deg_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree_provider', to_field='deg_provider_id'),
        ),
        migrations.AlterField(
            model_name='degree_enroll',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Student', to_field='student_id'),
        ),
        migrations.AlterField(
            model_name='degree_enroll_requirements',
            name='degree_provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.degree_provider', to_field='deg_provider_id'),
        ),
    ]
